namespace CloudAlarmOverlay.Core.Models;

public sealed record Device
{
    public long Id { get; init; }
    // Supplied manually by IT; never generated by the application.
    public required string DeviceId { get; init; }
    public string? DisplayName { get; init; }
    public DateTime? LastSeen { get; init; }
    public string? Version { get; init; }
}

